version: "3.9"
services:
  rtmp:
    build: ./rtmp
    ports:
      - "1935:1935"
      - "8000:8000"
    container_name: rtmp_server
    restart: always

  auth:
    build: ./auth
    container_name: auth_server
    restart: always
